# Generated by Django 5.2.5 on 2025-10-25 01:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo_numero', models.CharField(editable=False, help_text='Número de recibo autogenerado', max_length=20, unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total del pago', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_interes', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor destinado a intereses', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valor_capital', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor destinado a capital', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tipo', models.CharField(choices=[('INTERES', 'Solo Interés'), ('CAPITAL', 'Solo Capital'), ('MIXTO', 'Interés + Capital'), ('COMPLETO', 'Pago Completo')], default='MIXTO', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CONSIGNACION', 'Consignación'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=15)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia de transferencia/consignación', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('comprobante', models.FileField(blank=True, help_text='Comprobante de pago escaneado', null=True, upload_to='pagos/comprobantes/')),
                ('recibo_impreso', models.BooleanField(default=False)),
                ('anulado', models.BooleanField(default=False)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='loans.prestamo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-created_at'],
                'indexes': [models.Index(fields=['recibo_numero'], name='payments_pa_recibo__10146e_idx'), models.Index(fields=['fecha_pago'], name='payments_pa_fecha_p_340cfb_idx'), models.Index(fields=['-created_at'], name='payments_pa_created_d5e6c4_idx'), models.Index(fields=['prestamo', 'anulado'], name='payments_pa_prestam_5bae6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_interes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pagos', to='loans.prestamo')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
                'ordering': ['prestamo', 'numero_cuota'],
                'unique_together': {('prestamo', 'numero_cuota')},
            },
        ),
    ]
