# Generated by Django 5.2.5 on 2025-10-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion_principal', models.TextField()),
                ('direccion_secundaria', models.TextField(blank=True)),
                ('celular', models.CharField(max_length=15)),
                ('celular_alternativo', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CoDeudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('relacion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codeudores', to='loans.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_interes', models.CharField(choices=[('ANTICIPADO', 'Anticipado'), ('VENCIDO', 'Vencido')], default='VENCIDO', max_length=11)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('plazo_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('letra_foto', models.ImageField(blank=True, help_text='Foto de la letra o pagaré firmado', null=True, upload_to='prestamos/letras/%Y/%m/')),
                ('letra_foto_reverso', models.ImageField(blank=True, help_text='Foto del reverso de la letra (opcional)', null=True, upload_to='prestamos/letras/%Y/%m/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('MORA', 'En Mora'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_pago_completo', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='loans.cliente')),
                ('codeudor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.codeudor')),
                ('prestamista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='users.prestamista')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
